# Addin play
# Install Yarn
---
- name: "Add yarn repository."
  yum_repository:
    name: yarn
    description: Yarn Repository
    baseurl: https://dl.yarnpkg.com/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: "https://dl.yarnpkg.com/rpm/pubkey.gpg"
- name: "Update repos cache and install Yarn package."
  yum:
    name: yarn
    state: present
    update_cache: yes
- name: "Remove yarn from siteinfo."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "remove-package.yml"
  vars:
    package: yarn
- name: "Install yarn package to siteinfo."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "install-package.yml"
  vars:
    package: yarn
    service: siteinfo
