# Addin play
# Install Yarn
---
- name: Install RPM repository"
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    mode: 0644
- name: Install package
  package:
    name: yarn
    state: present
  register: task_result
  until: task_result is success
  retries: 5
  delay: 2
- name: Link user binary
  command: "{{ apnscp_root }}/bin/scripts/yum-post.php install --update yarn siteinfo"
  notify: Flush fsmount on Yarn install
