# Addin play
# Install Yarn
---
- name: Install RPM repository
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
    mode: 0644
- name: "Remove yarn from ssh."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "remove-package.yml"
  vars:
    package: yarn
- name: "Install yarn package."
  include_role:
    name: apnscp/initialize-filesystem-template
    tasks_from: "install-package.yml"
  vars:
    package: yarn
    service: siteinfo
